[package]
name = "build-utils"
version = "0.1.0"
edition = "2021"

# This is optional and only needed if you are providing shared Rust code.
[lib]
path = "src/lib.rs"

[build-dependencies]
risc0-build = { version = "0.20.1" }