version: "3"

environment:

processes:


  celestia-arabica-light-node:
    command: |
      celestia light start --core.ip validator-1.celestia-arabica-11.com --p2p.network arabica
    readiness_probe:
      exec:
        command: echo "true"

  celestia-arabica-light-node-synced:
    command: |
      sleep 10
      cargo run --bin wait-for-celestia-light-node
    depends_on:
      celestia-arabica-light-node:
        condition: process_healthy

  celestia-arabica-fund-account:
    command: |
      curl -X POST 'https://faucet.celestia-arabica-11.com/api/v1/faucet/give_me' \
      -H 'Content-Type: application/json' \
      -d "{\"address\": \"$CELESTIA_ADDRESS\", \"chainId\": \"arabica-11\"}" | \
      jq -e '.txHash' || echo "Error: txHash field not found in the response." >&2
      sleep 45
    depends_on:
      celestia-arabica-light-node-synced:
        condition: process_completed

  m1-da-light-node-verifier-tests:
    command: |
      cargo test -p m1-da-light-node-verifier -- --test-threads=1
    depends_on:
      celestia-arabica-light-node: 
        condition: process_healthy
      celestia-arabica-light-node-synced:
        condition: process_completed
      celestia-arabica-fund-account:
        condition: process_completed

  m1-da-light-node:
    command: |
      cargo run -p m1-da-light-node
    depends_on:
      m1-da-light-node-verifier-tests:
        condition: process_completed
      celestia-arabica-light-node:
        condition: process_healthy

    readiness_probe:
      exec:
        command: echo "true"

  m1-da-light-node-client-tests:
    command: |
      sleep 10
      cargo test -p m1-da-light-node-client -- --test-threads=1
    depends_on:
      celestia-arabica-light-node: 
        condition: process_healthy
      m1-da-light-node: 
        condition: process_healthy
      m1-da-light-node-verifier-tests:
        condition: process_completed
