[package]
name = "host"
version = "0.0.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true } 