[workspace.package]
authors = ["Movement Labs"]
edition = "2021"
repository = "https://github.com/movemntdev/sdk"
license = "Apache-2.0"

[workspace]
resolver = "2"
members = [
    "shared-sequencer/movement-sequencer",
]

# We exclude the zkfp crate because it involves system dependencies, these 
# should be managed by the nix.flake
# To build with the zkfp crate `cargo build -p zkfp`
exclude = [
    "zkfp/host",
    "zkfp/methods",
    "zkfp/methods/guest",
]

[workspace.dependencies]
# To try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
anyhow = "1.0"
risc0-zkvm = { version = "0.20.1",  features = ["std"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
move-vm-runtime = { path = "./zkfp/vendors/move/language/move-vm/runtime" }
move-vm-test-utils = { path = "./zkfp/vendors/move/language/move-vm/test-utils" }
move-binary-format = { path = "./zkfp/vendors/move/language/move-binary-format" }
move-vm-types = { path ="./zkfp/vendors/move/language/move-vm/types"}
move-core-types = { path="./zkfp/vendors/move/language/move-core/types" }
move-compiler = { path="./zkfp/vendors/move/language/move-compiler" }
move-stdlib = { path="./zkfp/vendors/move/language/move-stdlib" }

# ! this will not work only here to help debugging
tempfile = "3.2.0"
