[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.20.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"

move-vm-runtime = { path = "../vendors/move/language/move-vm/runtime" }
move-vm-test-utils = { path = "../vendors/move/language/move-vm/test-utils" }
move-binary-format = { path = "../vendors/move/language/move-binary-format" }
move-vm-types = { path ="../vendors/move/language/move-vm/types"}
move-core-types = { path="../vendors/move/language/move-core/types" }
move-compiler = { path="../vendors/move/language/move-compiler" }
move-stdlib = { path="../vendors/move/language/move-stdlib" }
anyhow = "1.0"
tempfile = "3.2.0"
