[package]
name = "hello_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "0.20.1", default-features = false, features = [ "std" ] }
move-vm-runtime = { path = "../../vendors/move/language/move-vm/runtime" }
move-vm-test-utils = { path = "../../vendors/move/language/move-vm/test-utils" }
move-binary-format = { path = "../../vendors/move/language/move-binary-format" }
move-vm-types = { path ="../../vendors/move/language/move-vm/types"}
move-core-types = { path="../../vendors/move/language/move-core/types" }
# move-compiler = { path="../../vendors/move/language/move-compiler" }

# ! this will not work only here to help debugging
tempfile = "3.2.0"