name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetches the main repo but skips automatic handling of submodules
          submodules: false
          fetch-depth: 0

      - name: cargo build
        run: cargo build --verbose

      - name: cargo test
        run: cargo test --verbose